services:
  flask:
    # build: server
    image: qfortier/mtgscan-server:3.0
    ports:
      - '5000:5000'
    links:
      - redis
    env_file:
      - redis/redis.env

  celery:
    # build: server
    image: qfortier/mtgscan-server:3.0
    command: "poetry run celery -A app.celery worker -P eventlet --loglevel=info"
    links:
      - redis
    env_file:
      - azure.env
      - redis/redis.env

  redis:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis:/usr/local/etc/redis
