services:
    redis:
        image: redis
        ports:
            - '6379:6379'

            
    flask:
        build: server
        image: regmtgscan.azurecr.io/server
        ports:
            - '5000:5000'
        links:
            - redis


    celery:
        build: server
        image: regmtgscan.azurecr.io/server
        command: "celery -A app.celery worker --loglevel=info"
        links:
            - redis
        environment:
            - AZURE_VISION_KEY
            - AZURE_VISION_ENDPOINT
