services:
  flask:
    image: mtgscanapp
    build: ./server
    restart: always
    ports:
      - '80:80'
    env_file:
      - redis/redis.env

  celery:
    image: mtgscanapp
    build: ./server
    restart: always
    command: "poetry run celery -A app.celery worker -P eventlet --loglevel=info"
    env_file:
      - redis/redis.env

  redis:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis:/usr/local/etc/redis
