services:
  flask:
    image: qfortier/mtgscan-server:4.0
    restart: always
    ports:
      - '80:80'
    links:
      - redis
    env_file:
      - redis/redis.env

  celery:
    image: qfortier/mtgscan-server:4.0
    restart: always
    command: "poetry run celery -A app.celery worker -P eventlet --loglevel=info"
    links:
      - redis
    env_file:
      - azure.env
      - redis/redis.env

  redis:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis:/usr/local/etc/redis
