services:
    flask:
        # build: server
        image: qfortier/mtgscan-server:2.0
        ports:
            - '5000:5000'
        links:
            - redis
        env_file:
            - .env

    celery:
        # build: server
        image: qfortier/mtgscan-server:2.0
        command: "poetry run celery -A app.celery worker -P eventlet --loglevel=info"
        links:
            - redis
        env_file:
            - .env

    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes # add pw for production
