services:
    flask:
        build: server
        image: regmtgscan.azurecr.io/server
        ports:
            - '80:5000'
        links:
            - redis

    celery:
        build: server
        image: regmtgscan.azurecr.io/server
        command: "celery -A app.celery worker --loglevel=info --uid=nobody"
        links:
            - redis
        environment:
            - AZURE_VISION_KEY
            - AZURE_VISION_ENDPOINT

    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes