services:
    flask:
        # build: server
        image: qfortier/mtgscan-server:2.0 # hosted on dockerhub
        ports:
            - '5000:5000'
        links:
            - redis

    celery:
        # build: server
        image: qfortier/mtgscan-server:2.0
        command: "celery -A app.celery worker --loglevel=info --uid=nobody"
        links:
            - redis
        env_file:
            - .env

    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes # add pw for production
